title: Binil's Blogs
subtitle: Code.. Build.. Repeat.. !!
description: >- # this means to ignore newlines until "baseurl:"
  Hi there.. I am a full stack web developer.. This is my personal blog and i would like to share my thoughts over here ..

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact Me
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: profile.png
author: Binil M K
author_bio: Hi, my name is Binil M K. This is my personal blog.
author_email: "cnctbinil@gmail.com"
author_location: India
author_website_url: "https://mkbinil.github.io"
typewrite-text: Software engineering professional with experience in Agile development methodologies. Passionate towards latest technologies and loves the whole process of developing a project into its completion.


author_work_experiences:
            - company_name: Petrolink Data Services
              company_logo: petrolink.png
              company_url: https://petrolink.com
              designation: Software Engineer
              description: Worked on various Petrolink Products
              visibility: true
            - company_name: IBS Software
              company_logo: ibs.png
              company_url: https://ibsplc.com
              designation: Software Engineer
              description: Worked on various IBS Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: petrolink.png
                project_title: Petrovault
                project_description: PetroVault
                project_url: 
                visibility: 
              - project_thumbnail: ibs.PNG
                project_title: IFlightMRO
                project_description: IFlightMRO
                project_url: 
                visibility: true

# social links
twitter_username: mkbinil
github_username:  mkbnil
facebook_username: binil sreenivasan
linkedin_username: Binil M K
behance_username: johndoe
instagram_username: mk_binil
medium_username: mkbinil
telegram_username: mkbinil
dribbble_username: mkbinil
flickr_username: mkbinil

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: Binil M K
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: mkbinil

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
